"""add index to statistics_data table

Revision ID: 97c6efc63e16
Revises: 3ac8dfcef7a4
Create Date: 2024-08-25 15:23:18.438670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97c6efc63e16"
down_revision: Union[str, None] = "3ac8dfcef7a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_statistics_data_user_reference", "statistics_data", type_="unique"
    )
    op.create_index(
        op.f("ix_statistics_data_user_reference"),
        "statistics_data",
        ["user_reference"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_statistics_data_user_reference"), table_name="statistics_data"
    )
    op.create_unique_constraint(
        "uq_statistics_data_user_reference",
        "statistics_data",
        ["user_reference"],
    )
    # ### end Alembic commands ###
