"""add on_delete parameter to child tables

Revision ID: 66d6ae29384b
Revises: 485efe19ff7f
Create Date: 2024-08-25 15:08:50.645224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66d6ae29384b"
down_revision: Union[str, None] = "485efe19ff7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_achievements_profile_id_profiles",
        "achievements",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_achievements_profile_id_profiles"),
        "achievements",
        "profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_english_mode_stats_stats_id_statistics_data",
        "english_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_english_mode_stats_stats_id_statistics_data"),
        "english_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_extended_mode_stats_stats_id_statistics_data",
        "extended_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_extended_mode_stats_stats_id_statistics_data"),
        "extended_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_extreme_mode_stats_stats_id_statistics_data",
        "extreme_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_extreme_mode_stats_stats_id_statistics_data"),
        "extreme_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_profiles_user_reference_users", "profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_profiles_user_reference_users"),
        "profiles",
        "users",
        ["user_reference"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_standard_mode_stats_stats_id_statistics_data",
        "standard_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_standard_mode_stats_stats_id_statistics_data"),
        "standard_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_statistics_data_user_reference_users",
        "statistics_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_statistics_data_user_reference_users"),
        "statistics_data",
        "users",
        ["user_reference"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_text_mode_stats_stats_id_statistics_data",
        "text_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_text_mode_stats_stats_id_statistics_data"),
        "text_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_user_mode_stats_stats_id_statistics_data",
        "user_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_mode_stats_stats_id_statistics_data"),
        "user_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_mode_stats_stats_id_statistics_data"),
        "user_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_mode_stats_stats_id_statistics_data",
        "user_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_text_mode_stats_stats_id_statistics_data"),
        "text_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_text_mode_stats_stats_id_statistics_data",
        "text_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_statistics_data_user_reference_users"),
        "statistics_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_statistics_data_user_reference_users",
        "statistics_data",
        "users",
        ["user_reference"],
        ["username"],
    )
    op.drop_constraint(
        op.f("fk_standard_mode_stats_stats_id_statistics_data"),
        "standard_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_standard_mode_stats_stats_id_statistics_data",
        "standard_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_profiles_user_reference_users"),
        "profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_profiles_user_reference_users",
        "profiles",
        "users",
        ["user_reference"],
        ["username"],
    )
    op.drop_constraint(
        op.f("fk_extreme_mode_stats_stats_id_statistics_data"),
        "extreme_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_extreme_mode_stats_stats_id_statistics_data",
        "extreme_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_extended_mode_stats_stats_id_statistics_data"),
        "extended_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_extended_mode_stats_stats_id_statistics_data",
        "extended_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_english_mode_stats_stats_id_statistics_data"),
        "english_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_english_mode_stats_stats_id_statistics_data",
        "english_mode_stats",
        "statistics_data",
        ["stats_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_achievements_profile_id_profiles"),
        "achievements",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_achievements_profile_id_profiles",
        "achievements",
        "profiles",
        ["profile_id"],
        ["id"],
    )
    # ### end Alembic commands ###
