"""create profile table

Revision ID: 738c8adfc969
Revises: 431c08a08700
Create Date: 2024-08-11 22:44:40.916169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "738c8adfc969"
down_revision: Union[str, None] = "431c08a08700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("touch_typing", sa.String(), nullable=False),
        sa.Column("keyboard_type", sa.String(), nullable=False),
        sa.Column("profession", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("about_user", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    # ### end Alembic commands ###
