"""add indexes to stats tables

Revision ID: 906aaf00746e
Revises: 1f628b727bf5
Create Date: 2024-08-25 15:35:35.922318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "906aaf00746e"
down_revision: Union[str, None] = "1f628b727bf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_english_mode_stats_added_at"),
        "english_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_english_mode_stats_stats_id"),
        "english_mode_stats",
        ["stats_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extended_mode_stats_added_at"),
        "extended_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extended_mode_stats_stats_id"),
        "extended_mode_stats",
        ["stats_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extreme_mode_stats_added_at"),
        "extreme_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extreme_mode_stats_stats_id"),
        "extreme_mode_stats",
        ["stats_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_standard_mode_stats_added_at"),
        "standard_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_standard_mode_stats_stats_id"),
        "standard_mode_stats",
        ["stats_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_text_mode_stats_added_at"),
        "text_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_text_mode_stats_stats_id"),
        "text_mode_stats",
        ["stats_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_mode_stats_added_at"),
        "user_mode_stats",
        ["added_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_mode_stats_stats_id"),
        "user_mode_stats",
        ["stats_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_mode_stats_stats_id"), table_name="user_mode_stats"
    )
    op.drop_index(
        op.f("ix_user_mode_stats_added_at"), table_name="user_mode_stats"
    )
    op.drop_index(
        op.f("ix_text_mode_stats_stats_id"), table_name="text_mode_stats"
    )
    op.drop_index(
        op.f("ix_text_mode_stats_added_at"), table_name="text_mode_stats"
    )
    op.drop_index(
        op.f("ix_standard_mode_stats_stats_id"),
        table_name="standard_mode_stats",
    )
    op.drop_index(
        op.f("ix_standard_mode_stats_added_at"),
        table_name="standard_mode_stats",
    )
    op.drop_index(
        op.f("ix_extreme_mode_stats_stats_id"), table_name="extreme_mode_stats"
    )
    op.drop_index(
        op.f("ix_extreme_mode_stats_added_at"), table_name="extreme_mode_stats"
    )
    op.drop_index(
        op.f("ix_extended_mode_stats_stats_id"),
        table_name="extended_mode_stats",
    )
    op.drop_index(
        op.f("ix_extended_mode_stats_added_at"),
        table_name="extended_mode_stats",
    )
    op.drop_index(
        op.f("ix_english_mode_stats_stats_id"), table_name="english_mode_stats"
    )
    op.drop_index(
        op.f("ix_english_mode_stats_added_at"), table_name="english_mode_stats"
    )
    # ### end Alembic commands ###
