"""create achievements table

Revision ID: d9bcf75fa1bf
Revises: 738c8adfc969
Create Date: 2024-08-11 23:03:13.394943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9bcf75fa1bf"
down_revision: Union[str, None] = "738c8adfc969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("forty_characters_per_minute", sa.Boolean(), nullable=False),
        sa.Column("fifty_characters_per_minute", sa.Boolean(), nullable=False),
        sa.Column("sixty_characters_per_minute", sa.Boolean(), nullable=False),
        sa.Column(
            "seventy_characters_per_minute", sa.Boolean(), nullable=False
        ),
        sa.Column(
            "eighty_characters_per_minute", sa.Boolean(), nullable=False
        ),
        sa.Column(
            "ninety_characters_per_minute", sa.Boolean(), nullable=False
        ),
        sa.Column(
            "one_hundred_characters_per_minute", sa.Boolean(), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_achievements_profile_id_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("achievements")
    # ### end Alembic commands ###
