"""add profile_photo_url column to profile table

Revision ID: 42b336058884
Revises: 906aaf00746e
Create Date: 2024-09-13 22:55:02.789341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42b336058884"
down_revision: Union[str, None] = "906aaf00746e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("profile_photo_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "profile_photo_url")
    # ### end Alembic commands ###
