"""add touch typing to profiles table

Revision ID: 62a7f965f7cf
Revises: 45d549ecfb42
Create Date: 2024-08-18 21:36:11.176541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62a7f965f7cf"
down_revision: Union[str, None] = "45d549ecfb42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("touch_typing", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "touch_typing")
    # ### end Alembic commands ###
