"""create tables for statistics data

Revision ID: 6b8c93216df5
Revises: a063fae5f80e
Create Date: 2024-08-12 16:55:36.232590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b8c93216df5"
down_revision: Union[str, None] = "a063fae5f80e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics_data",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_statistics_data_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statistics_data")),
        sa.UniqueConstraint(
            "user_id", name=op.f("uq_statistics_data_user_id")
        ),
    )
    op.create_table(
        "english_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_english_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_english_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_english_mode_stats_statistics_id")
        ),
    )
    op.create_table(
        "extended_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_extended_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extended_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_extended_mode_stats_statistics_id")
        ),
    )
    op.create_table(
        "extreme_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_extreme_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extreme_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_extreme_mode_stats_statistics_id")
        ),
    )
    op.create_table(
        "standard_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_standard_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standard_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_standard_mode_stats_statistics_id")
        ),
    )
    op.create_table(
        "text_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_text_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_text_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_text_mode_stats_statistics_id")
        ),
    )
    op.create_table(
        "user_mode_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("statistics_id", sa.Integer(), nullable=False),
        sa.Column(
            "accuracy_percentage_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column(
            "characters_per_minute_for_each_attempt",
            sa.ARRAY(sa.Integer()),
            nullable=False,
        ),
        sa.Column("average_accuracy", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statistics_id"],
            ["statistics_data.id"],
            name=op.f("fk_user_mode_stats_statistics_id_statistics_data"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_mode_stats")),
        sa.UniqueConstraint(
            "statistics_id", name=op.f("uq_user_mode_stats_statistics_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_mode_stats")
    op.drop_table("text_mode_stats")
    op.drop_table("standard_mode_stats")
    op.drop_table("extreme_mode_stats")
    op.drop_table("extended_mode_stats")
    op.drop_table("english_mode_stats")
    op.drop_table("statistics_data")
    # ### end Alembic commands ###
