"""change foreign key in statistics_data table

Revision ID: d3cfd5e23aac
Revises: 06304d566677
Create Date: 2024-08-17 18:15:56.382865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3cfd5e23aac"
down_revision: Union[str, None] = "06304d566677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statistics_data",
        sa.Column("user_reference", sa.String(length=20), nullable=False),
    )
    op.drop_constraint(
        "uq_statistics_data_user_id", "statistics_data", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_statistics_data_user_reference"),
        "statistics_data",
        ["user_reference"],
    )
    op.drop_constraint(
        "fk_statistics_data_user_id_users",
        "statistics_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_statistics_data_user_reference_users"),
        "statistics_data",
        "users",
        ["user_reference"],
        ["username"],
    )
    op.drop_column("statistics_data", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statistics_data",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_statistics_data_user_reference_users"),
        "statistics_data",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_statistics_data_user_id_users",
        "statistics_data",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_statistics_data_user_reference"),
        "statistics_data",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_statistics_data_user_id", "statistics_data", ["user_id"]
    )
    op.drop_column("statistics_data", "user_reference")
    # ### end Alembic commands ###
