"""update foreign key in achievements table

Revision ID: a063fae5f80e
Revises: 75044fc42b11
Create Date: 2024-08-12 16:36:22.282075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a063fae5f80e"
down_revision: Union[str, None] = "75044fc42b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_achievements_profile_id"), "achievements", ["profile_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_achievements_profile_id"), "achievements", type_="unique"
    )
    # ### end Alembic commands ###
