"""move register date to profile table

Revision ID: d81f751ad06e
Revises: a52df1e7724f
Create Date: 2024-08-18 21:18:31.881803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d81f751ad06e"
down_revision: Union[str, None] = "a52df1e7724f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("register_date", sa.DateTime(), nullable=False)
    )
    op.drop_column("users", "registration_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "registration_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("profiles", "register_date")
    # ### end Alembic commands ###
