"""update foreign key in profile table

Revision ID: 75044fc42b11
Revises: d9bcf75fa1bf
Create Date: 2024-08-12 16:32:44.587366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75044fc42b11"
down_revision: Union[str, None] = "d9bcf75fa1bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_profiles_user_id"), "profiles", ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_profiles_user_id"), "profiles", type_="unique")
    # ### end Alembic commands ###
