"""update foreign keys for stats tables

Revision ID: 6950a20524e4
Revises: 6b8c93216df5
Create Date: 2024-08-15 23:02:24.940121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6950a20524e4"
down_revision: Union[str, None] = "6b8c93216df5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_english_mode_stats_statistics_id_statistics_data",
        "english_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_english_mode_stats_statistics_id_statistics_data"),
        "english_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_extended_mode_stats_statistics_id_statistics_data",
        "extended_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_extended_mode_stats_statistics_id_statistics_data"),
        "extended_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_extreme_mode_stats_statistics_id_statistics_data",
        "extreme_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_extreme_mode_stats_statistics_id_statistics_data"),
        "extreme_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_standard_mode_stats_statistics_id_statistics_data",
        "standard_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_standard_mode_stats_statistics_id_statistics_data"),
        "standard_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_text_mode_stats_statistics_id_statistics_data",
        "text_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_text_mode_stats_statistics_id_statistics_data"),
        "text_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    op.drop_constraint(
        "fk_user_mode_stats_statistics_id_statistics_data",
        "user_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_mode_stats_statistics_id_statistics_data"),
        "user_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_mode_stats_statistics_id_statistics_data"),
        "user_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_mode_stats_statistics_id_statistics_data",
        "user_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_text_mode_stats_statistics_id_statistics_data"),
        "text_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_text_mode_stats_statistics_id_statistics_data",
        "text_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_standard_mode_stats_statistics_id_statistics_data"),
        "standard_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_standard_mode_stats_statistics_id_statistics_data",
        "standard_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_extreme_mode_stats_statistics_id_statistics_data"),
        "extreme_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_extreme_mode_stats_statistics_id_statistics_data",
        "extreme_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_extended_mode_stats_statistics_id_statistics_data"),
        "extended_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_extended_mode_stats_statistics_id_statistics_data",
        "extended_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_english_mode_stats_statistics_id_statistics_data"),
        "english_mode_stats",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_english_mode_stats_statistics_id_statistics_data",
        "english_mode_stats",
        "statistics_data",
        ["statistics_id"],
        ["id"],
    )
    # ### end Alembic commands ###
