"""add added_at column to stats tables

Revision ID: 1f628b727bf5
Revises: 97c6efc63e16
Create Date: 2024-08-25 15:32:36.572478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f628b727bf5"
down_revision: Union[str, None] = "97c6efc63e16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "english_mode_stats",
        sa.Column("added_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "extended_mode_stats",
        sa.Column("added_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "extreme_mode_stats",
        sa.Column("added_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "standard_mode_stats",
        sa.Column("added_at", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "text_mode_stats", sa.Column("added_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "user_mode_stats", sa.Column("added_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_mode_stats", "added_at")
    op.drop_column("text_mode_stats", "added_at")
    op.drop_column("standard_mode_stats", "added_at")
    op.drop_column("extreme_mode_stats", "added_at")
    op.drop_column("extended_mode_stats", "added_at")
    op.drop_column("english_mode_stats", "added_at")
    # ### end Alembic commands ###
