"""add index to profile table

Revision ID: ed3c5711b8ef
Revises: 66d6ae29384b
Create Date: 2024-08-25 15:17:56.931408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed3c5711b8ef"
down_revision: Union[str, None] = "66d6ae29384b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_profiles_user_reference", "profiles", type_="unique"
    )
    op.create_index(
        op.f("ix_profiles_user_reference"),
        "profiles",
        ["user_reference"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profiles_user_reference"), table_name="profiles")
    op.create_unique_constraint(
        "uq_profiles_user_reference", "profiles", ["user_reference"]
    )
    # ### end Alembic commands ###
