"""add index to achievements table

Revision ID: 3ac8dfcef7a4
Revises: ed3c5711b8ef
Create Date: 2024-08-25 15:19:49.545340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ac8dfcef7a4"
down_revision: Union[str, None] = "ed3c5711b8ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_achievements_profile_id", "achievements", type_="unique"
    )
    op.create_index(
        op.f("ix_achievements_profile_id"),
        "achievements",
        ["profile_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_achievements_profile_id"), table_name="achievements"
    )
    op.create_unique_constraint(
        "uq_achievements_profile_id", "achievements", ["profile_id"]
    )
    # ### end Alembic commands ###
