"""update profile table

Revision ID: 06304d566677
Revises: eab55ebd48ad
Create Date: 2024-08-16 21:49:32.613874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06304d566677"
down_revision: Union[str, None] = "eab55ebd48ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles", "touch_typing", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "profiles", "keyboard_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "profiles", "profession", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "profiles", "location", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "profiles", "about_user", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles", "about_user", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles", "location", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles", "profession", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles", "keyboard_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "profiles", "touch_typing", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
